# Server Port
server.port=8080

# Persistent Local File Database Configuration
spring.datasource.url=jdbc:h2:file:./data/neurodb;DB_CLOSE_ON_EXIT=FALSE;AUTO_RECONNECT=TRUE
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

# Keep Hibernate auto-update enabled
spring.jpa.hibernate.ddl-auto=update

# Hibernate / JPA Settings
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.jpa.hibernate.ddl-auto=update

# Enable H2 Web Console to view your data in the browser
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console